version: "3.8"
services:
  app:
    image: juwon0909/heady:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      ACTIVE_MODE: prod
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      FOOD_API_BASE_URL: ${{ secrets.FOOD_API_BASE_URL }}
      FOOD_API_SERVICE_KEY: ${{ secrets.FOOD_API_SERVICE_KEY }}
      GEMINI_API_URL: ${{ secrets.GEMINI_API_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}