version: "3.8"
services:
  app:
    image: juwon0909/heady:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
      ACTIVE_MODE: prod
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_URL: ${DB_URL}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      FOOD_API_BASE_URL: ${FOOD_API_BASE_URL}
      FOOD_API_SERVICE_KEY: ${FOOD_API_SERVICE_KEY}
      GEMINI_API_URL: ${GEMINI_API_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
