spring:
  profiles:
    active: local

jwt:
  secret-key: ${JWT_SECRET_KEY}
  accessToken-expiration-millis: 1800000
  refreshToken-expiration-millis: 1209600000
food:
  api:
    base-url: ${FOOD_API_BASE_URL}
    service-key: ${FOOD_API_SERVICE_KEY}
gemini:
  api:
    base-url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

